parameters:
#    me_panel_base.example.class: mePanel\BaseBundle\Example

services:
#    me_panel_base.example:
#        class: %me_panel_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
